version: '3.4'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  redistest:
    image: redistest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8383:8383
    depends_on:
      - redis