server:
  port: 8083
  ssl:
    enabled: true
    #    key-store: keystore.p12
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
  #    key-alias: bns-ssl


spring:
  redis:
    host: i8b306.p.ssafy.io
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i8b306.p.ssafy.io:3306/common_pjt?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace